--------------------------------------------------------
--  DDL for Sequence IC_ATTR_NBR_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  IC_ATTR_NBR_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1  CACHE 20 NOORDER  NOCYCLE ;
 
--------------------------------------------------------
--  DDL for Sequence IC_CATEGORY_NBR_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  IC_CATEGORY_NBR_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1  CACHE 20 NOORDER  NOCYCLE ;
 
--------------------------------------------------------
--  DDL for Sequence IC_ITEM_LOC_NBR_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  IC_ITEM_LOC_NBR_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1  CACHE 20 NOORDER  NOCYCLE ;
 
--------------------------------------------------------
--  DDL for Sequence IC_ITEM_MAST_NOMEN_NBR_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  IC_ITEM_MAST_NOMEN_NBR_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1  CACHE 20 NOORDER  NOCYCLE ;
 
--------------------------------------------------------
--  DDL for Sequence IC_ITEM_MAST_ORG_NBR_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  IC_ITEM_MAST_ORG_NBR_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1  CACHE 20 NOORDER  NOCYCLE ;
 
--------------------------------------------------------
--  DDL for Sequence IC_LOT_COST_HIST_NBR_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  IC_LOT_COST_HIST_NBR_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1  CACHE 20 NOORDER  NOCYCLE ;
 
 
 
 
 
--------------------------------------------------------
--  DDL for Table IC_ATTR
--------------------------------------------------------

  CREATE TABLE IC_ATTR 
   (	IC_ATTR_ID NUMBER(9,0) NOT NULL ENABLE, 
	ATTR_NM VARCHAR2(16) NOT NULL ENABLE, 
	ATTR_DESCR VARCHAR2(60) NOT NULL ENABLE, 
	ATTR_SEQ NUMBER(3,0), 
	REQR_FLG VARCHAR2(1) NOT NULL ENABLE, 
	ATTR_CONSTR_FLG VARCHAR2(1) NOT NULL ENABLE, 
	UT_USER_ID NUMBER(9,0) NOT NULL ENABLE, 
	LAST_MOD_DT DATE NOT NULL ENABLE, 
	 CHECK ( reqr_flg IN ('Y', 'N')) ENABLE, 
	 CHECK ( attr_constr_flg IN ('Y', 'N')) ENABLE, 
	 CONSTRAINT IC_ATTR_PK PRIMARY KEY (IC_ATTR_NBR) ENABLE, 
	 CONSTRAINT IC_ATTR_UK UNIQUE (ATTR_NM) ENABLE
   ) ;
 
--------------------------------------------------------
--  DDL for Table IC_ATTR_VAL
--------------------------------------------------------

  CREATE TABLE IC_ATTR_VAL 
   (	IC_ATTR_ID NUMBER(9,0) NOT NULL ENABLE, 
	ATTR_VAL VARCHAR2(20) NOT NULL ENABLE, 
	ATTR_VAL_DESCR VARCHAR2(60), 
	UT_USER_ID NUMBER(9,0) NOT NULL ENABLE, 
	LAST_MOD_DT DATE NOT NULL ENABLE, 
	 CONSTRAINT IC_ATTR_VAL_PK PRIMARY KEY (IC_ATTR_NBR, ATTR_VAL) ENABLE, 
	 CONSTRAINT IAV_IA_FK FOREIGN KEY (IC_ATTR_NBR)
	  REFERENCES IC_ATTR (IC_ATTR_NBR) ENABLE
   ) ;
 

  CREATE TABLE IC_CATEGORY 
   (	IC_CATEGORY_ID NUMBER(9,0) NOT NULL ENABLE, 
	IC_CATEGORY_NBR_PARENT NUMBER(9,0), 
	IC_CATEGORY_NM VARCHAR2(16) NOT NULL ENABLE, 
	IC_CATEGORY_DESCR VARCHAR2(30), 
	UT_USER_ID NUMBER(9,0) NOT NULL ENABLE, 
	LAST_MOD_DT DATE NOT NULL ENABLE, 
	PO_VND_SET_HDR_ID NUMBER(9,0), 
	IC_CATEGORY_COLLATE_ID NUMBER(4,0), 
	PRINT_MFR_FLG VARCHAR2(1), 
	 CONSTRAINT IC_CATEGORY_PK PRIMARY KEY (IC_CATEGORY_NBR) ENABLE, 
	 CONSTRAINT IC_CATEGORY_UK UNIQUE (IC_CATEGORY_NM) ENABLE, 
	 CONSTRAINT IC_IC_FK FOREIGN KEY (IC_CATEGORY_NBR_PARENT)
	  REFERENCES IC_CATEGORY (IC_CATEGORY_NBR) ENABLE, 
	 CONSTRAINT IC_PVSH_FK FOREIGN KEY (PO_VND_SET_HDR_NBR)
	  REFERENCES PO_VND_SET_HDR (PO_VND_SET_HDR_NBR) ENABLE
   ) ;
 
--------------------------------------------------------
--  DDL for Table IC_CATEGORY_ATTR
--------------------------------------------------------

  CREATE TABLE IC_CATEGORY_ATTR 
   (	IC_CATEGORY_ID NUMBER(9,0) NOT NULL ENABLE, 
	IC_ATTR_ID NUMBER(9,0) NOT NULL ENABLE, 
	UT_USER_ID NUMBER(9,0) NOT NULL ENABLE, 
	LAST_MOD_DT DATE NOT NULL ENABLE, 
	 CONSTRAINT IC_CATEGORY_ATTR_PK PRIMARY KEY (IC_CATEGORY_NBR, IC_ATTR_NBR) ENABLE, 
	 CONSTRAINT ICA_IA_FK FOREIGN KEY (IC_ATTR_NBR)
	  REFERENCES IC_ATTR (IC_ATTR_NBR) ENABLE, 
	 CONSTRAINT ICA_IC_FK FOREIGN KEY (IC_CATEGORY_NBR)
	  REFERENCES IC_CATEGORY (IC_CATEGORY_NBR) ENABLE
   ) ;
 
 
--------------------------------------------------------
--  DDL for Table IC_CATEGORY_NARR
--------------------------------------------------------

  CREATE TABLE IC_CATEGORY_NARR 
   (	IC_CATEGORY_ID NUMBER(9,0) NOT NULL ENABLE, 
	IC_CATEGORY_NARR VARCHAR2(4000) NOT NULL ENABLE, 
	UT_USER_ID NUMBER(9,0) NOT NULL ENABLE, 
	LAST_MOD_DT DATE NOT NULL ENABLE, 
	 CONSTRAINT IC_CATEGORY_NARR_PK PRIMARY KEY (IC_CATEGORY_NBR) ENABLE, 
	 CONSTRAINT ICNARR_IC_FK FOREIGN KEY (IC_CATEGORY_NBR)
	  REFERENCES IC_CATEGORY (IC_CATEGORY_NBR) ENABLE
   ) ;
 
 
 
 
--------------------------------------------------------
--  DDL for Table IC_ITEM_ATTR
--------------------------------------------------------

  CREATE TABLE IC_ITEM_ATTR 
   (	ITEM_ID NUMBER(9,0) NOT NULL ENABLE, 
	IC_ATTR_ID NUMBER(9,0) NOT NULL ENABLE, 
	ATTR_VAL VARCHAR2(20) NOT NULL ENABLE, 
	UT_USER_ID NUMBER(9,0) NOT NULL ENABLE, 
	LAST_MOD_DT DATE NOT NULL ENABLE, 
	 CONSTRAINT IC_ITEM_ATTR_PK PRIMARY KEY (ITEM_NBR, IC_ATTR_NBR) ENABLE, 
	 CONSTRAINT IIA_IA_FK FOREIGN KEY (IC_ATTR_NBR)
	  REFERENCES IC_ATTR (IC_ATTR_NBR) ENABLE, 
	 CONSTRAINT IIA_IIM_FK FOREIGN KEY (ITEM_NBR)
	  REFERENCES IC_ITEM_MAST (ITEM_NBR) ENABLE
   ) ;
 
 
 

  CREATE TABLE IC_ITEM_MAST 
   (	
	ITEM_ID NUMBER(9,0) NOT NULL ENABLE, 
	ITEM_CD VARCHAR2(50) NOT NULL ENABLE, 
	ITEM_DESCR VARCHAR2(50) NOT NULL ENABLE, 
	STK_UM VARCHAR2(3) NOT NULL ENABLE, 
	SELL_UM VARCHAR2(3), 
	STD_COST NUMBER(17,6), 
	LIST_PRICE NUMBER(17,6), 
	UPC_CD VARCHAR2(20), 
	EAN VARCHAR2(50), 
	QTY_PER_BOX NUMBER(7,0), 
	BOX_PER_CTN NUMBER(7,0), 
	SLS_QTY_MIN NUMBER(7,0), 
	SLS_QTY_INCR NUMBER(7,0), 
	REPLEN_QTY_MIN NUMBER(7,0), 
	REPLEN_QTY_INCR NUMBER(7,0), 
	IC_CATEGORY_ID NUMBER(9,0) NOT NULL ENABLE, 
	SER_NBR_REQR_FLG VARCHAR2(1) NOT NULL ENABLE, 
	MFR_SER_NBR_REQR_FLG VARCHAR2(1) NOT NULL ENABLE, 
	UT_USER_ID NUMBER(9,0) NOT NULL ENABLE, 
	LAST_MOD_DT DATE NOT NULL ENABLE, 
	SELL_FLG VARCHAR2(1), 
	HARMONIZED_CD VARCHAR2(15), 
	PLAN_BUCKET_SZ NUMBER(3,0), 
	CURR_CD VARCHAR2(3), 
	REQR_MFR_FLG VARCHAR2(1) NOT NULL ENABLE, 
	SHELF_LIFE_DY NUMBER(5,0), 
	LEAD_TM_DY NUMBER(5,0), 
	INDIV_NBR_BUYER NUMBER(9,0), 
	STAT_ID VARCHAR2(1) NOT NULL ENABLE, 
	PICK_SCAN_ID VARCHAR2(1) NOT NULL ENABLE, 
	INTRO_DT DATE NOT NULL ENABLE, 
	SPLIT_AT_BIN_FLG VARCHAR2(1) NOT NULL ENABLE, 
	LABEL_NM_BOX VARCHAR2(20), 
	IC_RECV_RULE_CD VARCHAR2(16), 
	CYCLE_CNT_RULE_CD VARCHAR2(16), 
	FIFO_DT_ID VARCHAR2(1) NOT NULL ENABLE, 
	REPLEN_TYPE_ID VARCHAR2(1) DEFAULT 'B' NOT NULL ENABLE, 
	ITEM_NBR_PRIMARY NUMBER(9,0), 
	ITEM_NBR_SUPERSEDE NUMBER(9,0), 
	SCHED_QTY_OPTIMAL NUMBER(7,0), 
	IMG_IMAGE_SET_HDR_ID NUMBER(9,0), 
	ITEM_WGHT NUMBER(12,5), 
	CTN_VOLUME NUMBER(10,2), 
	 CHECK ( non_stk_flg IN ('Y', 'N')) ENABLE, 
	 CHECK ( ser_nbr_reqr_flg IN ('Y', 'N')) ENABLE, 
	 CHECK ( mfr_ser_nbr_reqr_flg IN ('Y', 'N')) ENABLE, 
	 CHECK ( inspect_reqr_flg IN ('Y', 'N')) ENABLE, 
	 CHECK ( mfr_lot_ctrl_flg IN ('Y', 'N')) ENABLE, 
	 CHECK ( kit_flg IN ('Y', 'N')) ENABLE, 
	 CHECK ( price_chg_flg IN ('Y', 'N')) ENABLE, 
	 CONSTRAINT IC_ITEM_MAST_PK PRIMARY KEY (ITEM_NBR) ENABLE, 
	 CONSTRAINT IC_ITEM_MAST_UK UNIQUE (ITEM_CD) ENABLE, 
	 CHECK ( sell_flg in ('Y','N')) ENABLE, 
	 CHECK (reqr_mfr_flg in ('Y', 'N')) ENABLE, 
	 CHECK (stat_id IN ('A','I','S')) ENABLE, 
	 CHECK (split_at_bin_flg in ('Y', 'N')) ENABLE, 
	 CONSTRAINT IIM_CHECK_FIFO_DT_ID CHECK (FIFO_dt_ID IN ('R', 'M', 'E')) ENABLE, 
	 CONSTRAINT IIM_CHECK_REPLEN_TYPE_ID CHECK (REPLEN_TYPE_ID IN ('B', 'M', 'A', 'K', 'D')) ENABLE, 
	 CONSTRAINT IIM_IC_FK FOREIGN KEY (IC_CATEGORY_NBR)
	  REFERENCES IC_CATEGORY (IC_CATEGORY_NBR) ENABLE, 
	 CONSTRAINT IIM_IIM_PRIMARY_FK FOREIGN KEY (ITEM_NBR_PRIMARY)
	  REFERENCES IC_ITEM_MAST (ITEM_NBR) ENABLE, 
	 CONSTRAINT IIM_IIM_SUPERSEDE_FK FOREIGN KEY (ITEM_NBR_SUPERSEDE)
	  REFERENCES IC_ITEM_MAST (ITEM_NBR) ENABLE, 
	 CONSTRAINT IIM_IU_SELL_FK FOREIGN KEY (SELL_UM)
	  REFERENCES IC_UM (UM_ID) ENABLE, 
	 CONSTRAINT IIM_IU_STK_FK FOREIGN KEY (STK_UM)
	  REFERENCES IC_UM (UM_ID) ENABLE, 
	 CONSTRAINT IIM_IMG_IISH_FK FOREIGN KEY (IMG_IMAGE_SET_HDR_NBR)
	  REFERENCES IMG_IMAGE_SET_HDR (IMG_IMAGE_SET_HDR_NBR) ENABLE, 
	 CONSTRAINT IIM_NI_FK FOREIGN KEY (INDIV_NBR_BUYER)
	  REFERENCES NA_INDIV (INDIV_NBR) ENABLE, 
	 CONSTRAINT IIM_IRR_FK FOREIGN KEY (IC_RECV_RULE_CD)
	  REFERENCES IC_RECV_RULE (IC_RECV_RULE_CD) ENABLE, 
	 CONSTRAINT IIM_ULC_FK FOREIGN KEY (LABEL_NM_BOX)
	  REFERENCES UT_LABEL_CLASS (LABEL_NM) ENABLE, 
	 CONSTRAINT IIM_WPSI_FK FOREIGN KEY (PICK_SCAN_ID)
	  REFERENCES WH_PICK_SCAN_ID (PICK_SCAN_ID) ENABLE, 
	 CONSTRAINT IIM_CUR_FK FOREIGN KEY (CURR_CD)
	  REFERENCES CURRENCY (CURR_CD) ENABLE, 
	 CONSTRAINT IIM_CCR_FK FOREIGN KEY (CYCLE_CNT_RULE_CD)
	  REFERENCES CYCLE_CNT_RULE (CYCLE_CNT_RULE_CD) ENABLE
   ) ;
 
   COMMENT ON COLUMN IC_ITEM_MAST.FIFO_DT_ID IS 'R-Receipt Date, M-Manufacture Date, E-Expiration Date';
 
   COMMENT ON COLUMN IC_ITEM_MAST.REPLEN_TYPE_ID IS 'B-Buy, M-Manufacture,
	A-Assemble, K-Kit, D-Do not Buy';
 
 
--------------------------------------------------------
--  DDL for Table IC_ITEM_MAST_NOMEN
--------------------------------------------------------

  CREATE TABLE IC_ITEM_MAST_NOMEN 
   (	ITEM_ID NUMBER(9,0) NOT NULL ENABLE, 
	ORG_NBR_NOMEN NUMBER(9,0) NOT NULL ENABLE, 
	ITEM_CD_NOMEN VARCHAR2(50) NOT NULL ENABLE, 
	ITEM_DESCR_NOMEN VARCHAR2(50), 
	UT_USER_ID NUMBER(9,0) NOT NULL ENABLE, 
	LAST_MOD_DT DATE NOT NULL ENABLE, 
	DISPLAY_FLG VARCHAR2(1) NOT NULL ENABLE, 
	 CONSTRAINT IC_ITEM_MAST_NOMEN_PK PRIMARY KEY (ITEM_NBR, ORG_NBR_NOMEN, ITEM_CD_NOMEN) ENABLE, 
	 CHECK (display_flg in ('Y','N')) ENABLE, 
	 CONSTRAINT IIMN_IIM_FK FOREIGN KEY (ITEM_NBR)
	  REFERENCES IC_ITEM_MAST (ITEM_NBR) ENABLE, 
	 CONSTRAINT IIMN_NO_FK FOREIGN KEY (ORG_NBR_NOMEN)
	  REFERENCES NA_ORG (ORG_NBR) ENABLE
   ) ;
 
 

 
 
--------------------------------------------------------
--  DDL for Table IC_ITEM_NARR
--------------------------------------------------------

  CREATE TABLE IC_ITEM_NARR 
   (	ITEM_ID NUMBER(9,0) NOT NULL ENABLE, 
	ITEM_NARR VARCHAR2(4000) NOT NULL ENABLE, 
	UT_USER_ID NUMBER(9,0) NOT NULL ENABLE, 
	LAST_MOD_DT DATE NOT NULL ENABLE, 
	 CONSTRAINT IC_ITEM_NARR_PK PRIMARY KEY (ITEM_NBR) ENABLE, 
	 CONSTRAINT IINARR_IIM_FK FOREIGN KEY (ITEM_NBR)
	  REFERENCES IC_ITEM_MAST (ITEM_NBR) ENABLE
   ) ;
 
 
 
 
 
 
 
 
--------------------------------------------------------
--  DDL for Table IC_LOT_IMAGE
--------------------------------------------------------

  CREATE TABLE IC_LOT_IMAGE 
   (	LOT_ID NUMBER(9,0) NOT NULL ENABLE, 
	IMG_IMAGE_SET_HDR_ID NUMBER(9,0) NOT NULL ENABLE, 
	CERT_CD VARCHAR2(8), 
	QA_APPRV_FLG VARCHAR2(1) NOT NULL ENABLE, 
	 CHECK (QA_APPRV_FLG IN ('Y', 'N')) ENABLE, 
	 CONSTRAINT IC_LOT_IMAGE_PK PRIMARY KEY (LOT_NBR, CERT_CD, IMG_IMAGE_SET_HDR_NBR) ENABLE, 
	 CONSTRAINT ILI_ICC_FK FOREIGN KEY (CERT_CD)
	  REFERENCES IC_CERT_CD (CERT_CD) ENABLE, 
	 CONSTRAINT ILI_IMG_IISH_FK FOREIGN KEY (IMG_IMAGE_SET_HDR_NBR)
	  REFERENCES IMG_IMAGE_SET_HDR (IMG_IMAGE_SET_HDR_NBR) ENABLE, 
	 CONSTRAINT ILI_ILM_FK FOREIGN KEY (LOT_NBR)
	  REFERENCES IC_LOT_MAST (LOT_NBR) ENABLE
   ) ;
 
 
 
 
 
--------------------------------------------------------
--  DDL for Table IC_UM
--------------------------------------------------------

  CREATE TABLE IC_UM 
   (	UM_ID VARCHAR2(3) NOT NULL ENABLE, 
	UM_ID_DESCR VARCHAR2(30) NOT NULL ENABLE, 
	UM_FAMILY VARCHAR2(8) NOT NULL ENABLE, 
	UT_USER_ID NUMBER(9,0) NOT NULL ENABLE, 
	LAST_MOD_DT DATE NOT NULL ENABLE, 
	UM_PRECISION NUMBER(1,0), 
	 CONSTRAINT IC_UM_PK PRIMARY KEY (UM_ID) ENABLE, 
	 CONSTRAINT IU_IUH_FK FOREIGN KEY (UM_FAMILY)
	  REFERENCES IC_UM_HDR (UM_FAMILY) ENABLE
   ) ;
 
--------------------------------------------------------
--  DDL for Table IC_UM_CNVT
--------------------------------------------------------

  CREATE TABLE IC_UM_CNVT 
   (	UM_ID_FROM VARCHAR2(3) NOT NULL ENABLE, 
	UM_ID_TO VARCHAR2(3) NOT NULL ENABLE, 
	UM_CNVT_FACT NUMBER(13,5) NOT NULL ENABLE, 
	UT_USER_ID NUMBER(9,0) NOT NULL ENABLE, 
	LAST_MOD_DT DATE NOT NULL ENABLE, 
	 CONSTRAINT IC_UM_CNVT_PK PRIMARY KEY (UM_ID_FROM, UM_ID_TO) ENABLE, 
	 CONSTRAINT IUC_FROM_IU_FK FOREIGN KEY (UM_ID_FROM)
	  REFERENCES IC_UM (UM_ID) ENABLE, 
	 CONSTRAINT IUC_TO_IU_FK FOREIGN KEY (UM_ID_TO)
	  REFERENCES IC_UM (UM_ID) ENABLE
   ) ;
 
--------------------------------------------------------
--  DDL for Table IC_UM_CNVT_ITEM
--------------------------------------------------------

  CREATE TABLE IC_UM_CNVT_ITEM 
   (	ITEM_ID NUMBER(9,0) NOT NULL ENABLE, 
	UM_ID_FROM VARCHAR2(3) NOT NULL ENABLE, 
	UM_ID_TO VARCHAR2(3) NOT NULL ENABLE, 
	UM_CNVT_FACT_ITEM NUMBER(13,5) NOT NULL ENABLE, 
	UT_USER_ID NUMBER(9,0) NOT NULL ENABLE, 
	LAST_MOD_DT DATE NOT NULL ENABLE, 
	 CONSTRAINT IC_UM_CNVT_ITEM_PK PRIMARY KEY (ITEM_NBR, UM_ID_FROM, UM_ID_TO) ENABLE, 
	 CONSTRAINT IUCI_IIM_FK FOREIGN KEY (ITEM_NBR)
	  REFERENCES IC_ITEM_MAST (ITEM_NBR) ENABLE, 
	 CONSTRAINT IUCI_IU_FROM_FK FOREIGN KEY (UM_ID_FROM)
	  REFERENCES IC_UM (UM_ID) ENABLE, 
	 CONSTRAINT IUCI_IU_TO_FK FOREIGN KEY (UM_ID_TO)
	  REFERENCES IC_UM (UM_ID) ENABLE
   ) ;
 
--------------------------------------------------------
--  DDL for Table IC_UM_HDR
--------------------------------------------------------

  CREATE TABLE IC_UM_HDR 
   (	UM_FAMILY VARCHAR2(8) NOT NULL ENABLE, 
	UM_FAMILY_DESCR VARCHAR2(60), 
	UT_USER_ID NUMBER(9,0) NOT NULL ENABLE, 
	LAST_MOD_DT DATE NOT NULL ENABLE, 
	 CONSTRAINT IC_UM_HDR_PK PRIMARY KEY (UM_FAMILY) ENABLE
   ) ;
 
--------------------------------------------------------
--  DDL for Table IC_VND_ONHAND
--------------------------------------------------------

  CREATE TABLE IC_VND_ONHAND 
   (	IC_VND_ONHAND_ID NUMBER(9,0) NOT NULL ENABLE, 
	ITEM_ID NUMBER(9,0), 
	ITEM_CD_VND VARCHAR2(50) NOT NULL ENABLE, 
	ORG_NBR_VND NUMBER(9,0) NOT NULL ENABLE, 
	LOAD_DT DATE NOT NULL ENABLE, 
	QTY_ON_HAND NUMBER(13,5) NOT NULL ENABLE, 
	STK_UM VARCHAR2(3) NOT NULL ENABLE, 
	UNIT_PRICE NUMBER(17,6), 
	 CONSTRAINT IC_VND_ONHAND_PK PRIMARY KEY (IC_VND_ONHAND_NBR) ENABLE, 
	 CONSTRAINT IC_VND_ONHAND_UK UNIQUE (ITEM_CD_VND, ORG_NBR_VND, LOAD_DT) ENABLE, 
	 CONSTRAINT IVO_IIM_FK FOREIGN KEY (ITEM_NBR)
	  REFERENCES IC_ITEM_MAST (ITEM_NBR) DISABLE, 
	 CONSTRAINT IVO_IU_FK FOREIGN KEY (STK_UM)
	  REFERENCES IC_UM (UM_ID) DISABLE, 
	 CONSTRAINT IVO_PVM_FK FOREIGN KEY (ORG_NBR_VND)
	  REFERENCES PO_VND_MAST (ORG_NBR_VND) DISABLE
   ) ;
 
 
 
 
